import { ERROR_CODES as BASIC_ERROR_CODES } from '@packages/layer-basic/server/errors'

// Authentication errors
const AUTH_ERRORS = {
  AUTH_INVALID_VERIFICATION_CODE: 'AUTH_INVALID_VERIFICATION_CODE',
  AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',
  AUTH_OTP_EMAIL_RATE_LIMITED: 'AUTH_OTP_EMAIL_RATE_LIMITED',
  AUTH_OTP_IP_RATE_LIMITED: 'AUTH_OTP_IP_RATE_LIMITED',
  AUTH_TURNSTILE_FAILED: 'AUTH_TURNSTILE_FAILED',
  AUTH_USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_VERIFICATION_CODE_EXPIRED: 'AUTH_VERIFICATION_CODE_EXPIRED',
  // better-auth internal error code (keep original naming for compatibility)
  INVALID_EMAIL: 'INVALID_EMAIL',
} as const

// Impersonation errors
const IMPERSONATION_ERRORS = {
  IMPERSONATION_INVALID_TICKET: 'IMPERSONATION_INVALID_TICKET',
  IMPERSONATION_TICKET_EXPIRED: 'IMPERSONATION_TICKET_EXPIRED',
  IMPERSONATION_USER_NOT_FOUND: 'IMPERSONATION_USER_NOT_FOUND',
  IMPERSONATION_WRITE_FORBIDDEN: 'IMPERSONATION_WRITE_FORBIDDEN',
} as const

// Invite code errors
const INVITE_CODE_ERRORS = {
  INVITE_CODE_EXPIRED: 'INVITE_CODE_EXPIRED',
  INVITE_CODE_INVALID: 'INVITE_CODE_INVALID',
  INVITE_CODE_REQUIRED: 'INVITE_CODE_REQUIRED',
  INVITE_CODE_USAGE_EXCEEDED: 'INVITE_CODE_USAGE_EXCEEDED',
} as const

// Combine all error codes
export const ERROR_CODES = {
  ...BASIC_ERROR_CODES,
  ...AUTH_ERRORS,
  ...IMPERSONATION_ERRORS,
  ...INVITE_CODE_ERRORS,
} as const

export type ErrorCode = keyof typeof ERROR_CODES
