packages:
  - packages/*

catalog:
  '@paralleldrive/cuid2': ^3.3.0
  '@polymarbot/shared': ^0.8.1
  '@polymarket/builder-relayer-client': ^0.0.8
  '@primeuix/themes': ^2.0.3
  '@primevue/nuxt-module': ^4.5.5
  '@prisma/adapter-pg': ^7.7.0
  '@prisma/client': ^7.7.0
  '@prisma/client-runtime-utils': ^7.7.0
  '@sentry/vue': ^10.48.0
  '@unhead/vue': ^2.1.13
  better-auth: ^1.6.3
  clsx: ^2.1.1
  dayjs: ^1.11.20
  echarts: ^6.0.0
  primeicons: ^7.0.0
  primevue: ^4.5.5
  qrcode: ^1.5.4
  tailwind-merge: ^3.5.0
  tailwindcss-primeui: ^0.6.1
  viem: ^2.47.18
  vue-echarts: ^8.0.1
  vue-gtag: ^3.7.0
  vue-i18n: ^11.3.2
  vue-router: ^5.0.4
  zod: 4.3.6
