/**
 * Unified error codes for lib utilities
 * These codes should be used by lib functions to return structured errors
 * The calling side (API routes, components) should handle internationalization
 */

// Common errors
const COMMON_ERRORS = {
  COMMON_FORBIDDEN_ERROR: 'COMMON_FORBIDDEN_ERROR',
  COMMON_NETWORK_ERROR: 'COMMON_NETWORK_ERROR',
  COMMON_NOT_FOUND_ERROR: 'COMMON_NOT_FOUND_ERROR',
  COMMON_RATE_LIMIT_EXCEEDED: 'COMMON_RATE_LIMIT_EXCEEDED',
  COMMON_SERVER_ERROR: 'COMMON_SERVER_ERROR',
  COMMON_TIMEOUT_ERROR: 'COMMON_TIMEOUT_ERROR',
  COMMON_UNAUTHORIZED_ERROR: 'COMMON_UNAUTHORIZED_ERROR',
  COMMON_UNKNOWN_ERROR: 'COMMON_UNKNOWN_ERROR',
  COMMON_VALIDATION_ERROR: 'COMMON_VALIDATION_ERROR',
} as const

// Authentication errors
const AUTH_ERRORS = {
  AUTH_INVALID_VERIFICATION_CODE: 'AUTH_INVALID_VERIFICATION_CODE',
  AUTH_OAUTH_FAILED: 'AUTH_OAUTH_FAILED',
  AUTH_OTP_EMAIL_RATE_LIMITED: 'AUTH_OTP_EMAIL_RATE_LIMITED',
  AUTH_OTP_IP_RATE_LIMITED: 'AUTH_OTP_IP_RATE_LIMITED',
  AUTH_TURNSTILE_FAILED: 'AUTH_TURNSTILE_FAILED',
  AUTH_USER_ALREADY_EXISTS: 'AUTH_USER_ALREADY_EXISTS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_VERIFICATION_CODE_EXPIRED: 'AUTH_VERIFICATION_CODE_EXPIRED',
  // better-auth internal error code (keep original naming for compatibility)
  INVALID_EMAIL: 'INVALID_EMAIL',
} as const

// Bot errors
const BOT_ERRORS = {
  BOT_ALREADY_EXISTS: 'BOT_ALREADY_EXISTS',
  BOT_ENABLED_CANNOT_DELETE: 'BOT_ENABLED_CANNOT_DELETE',
  BOT_ENABLED_CANNOT_MODIFY: 'BOT_ENABLED_CANNOT_MODIFY',
  BOT_NOT_FOUND: 'BOT_NOT_FOUND',
  BOT_WALLET_DEPLOYING: 'BOT_WALLET_DEPLOYING',
  BOT_WALLET_INSUFFICIENT_BALANCE: 'BOT_WALLET_INSUFFICIENT_BALANCE',
  BOT_WALLET_MARKET_IN_USE: 'BOT_WALLET_MARKET_IN_USE',
} as const

// Wallet errors
const WALLET_ERRORS = {
  WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
  WALLET_ALREADY_IN_USE: 'WALLET_ALREADY_IN_USE',
  WALLET_CREATION_FAILED: 'WALLET_CREATION_FAILED',
  WALLET_DEPLOYING: 'WALLET_DEPLOYING',
  WALLET_HAS_BOTS: 'WALLET_HAS_BOTS',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_INVALID_PRIVATE_KEY: 'WALLET_INVALID_PRIVATE_KEY',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_WITHDRAW_FAILED: 'WALLET_WITHDRAW_FAILED',
} as const

// Strategy errors
const STRATEGY_ERRORS = {
  STRATEGY_ALREADY_EXISTS: 'STRATEGY_ALREADY_EXISTS',
  STRATEGY_HAS_BOTS: 'STRATEGY_HAS_BOTS',
  STRATEGY_INTERVAL_NOT_MODIFIABLE: 'STRATEGY_INTERVAL_NOT_MODIFIABLE',
  STRATEGY_INVALID_JSON: 'STRATEGY_INVALID_JSON',
  STRATEGY_NO_BUY_STEPS: 'STRATEGY_NO_BUY_STEPS',
  STRATEGY_NOT_FOUND: 'STRATEGY_NOT_FOUND',
} as const

// Subscription errors
const SUBSCRIPTION_ERRORS = {
  SUBSCRIPTION_BOT_LIMIT_EXCEEDED: 'SUBSCRIPTION_BOT_LIMIT_EXCEEDED',
  SUBSCRIPTION_STATS_ACCESS_DENIED: 'SUBSCRIPTION_STATS_ACCESS_DENIED',
  SUBSCRIPTION_STRATEGY_AMOUNT_EXCEEDED: 'SUBSCRIPTION_STRATEGY_AMOUNT_EXCEEDED',
  SUBSCRIPTION_STRATEGY_LIMIT_EXCEEDED: 'SUBSCRIPTION_STRATEGY_LIMIT_EXCEEDED',
  SUBSCRIPTION_WALLET_LIMIT_EXCEEDED: 'SUBSCRIPTION_WALLET_LIMIT_EXCEEDED',
} as const

// Payment errors
const PAYMENT_ERRORS = {
  PAYMENT_CHARGE_CREATION_FAILED: 'PAYMENT_CHARGE_CREATION_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
} as const

// Invite code errors
const INVITE_CODE_ERRORS = {
  INVITE_CODE_EXPIRED: 'INVITE_CODE_EXPIRED',
  INVITE_CODE_INVALID: 'INVITE_CODE_INVALID',
  INVITE_CODE_REQUIRED: 'INVITE_CODE_REQUIRED',
  INVITE_CODE_USAGE_EXCEEDED: 'INVITE_CODE_USAGE_EXCEEDED',
} as const

// Internal API errors
const INTERNAL_API_ERRORS = {
  INTERNAL_API_KEY_INVALID: 'INTERNAL_API_KEY_INVALID',
  INTERNAL_API_KEY_MISSING: 'INTERNAL_API_KEY_MISSING',
} as const

// Combine all error codes
export const ERROR_CODES = {
  ...COMMON_ERRORS,
  ...AUTH_ERRORS,
  ...BOT_ERRORS,
  ...WALLET_ERRORS,
  ...STRATEGY_ERRORS,
  ...SUBSCRIPTION_ERRORS,
  ...PAYMENT_ERRORS,
  ...INVITE_CODE_ERRORS,
  ...INTERNAL_API_ERRORS,
} as const

export type ErrorCode = keyof typeof ERROR_CODES
