import { ERROR_CODES as BASIC_ERROR_CODES } from '@packages/layer-basic/server/errors'
import { ERROR_CODES as AUTH_ERROR_CODES } from '@packages/layer-auth/server/errors'

// Bot errors
const BOT_ERRORS = {
  BOT_ALREADY_EXISTS: 'BOT_ALREADY_EXISTS',
  BOT_ENABLED_CANNOT_DELETE: 'BOT_ENABLED_CANNOT_DELETE',
  BOT_ENABLED_CANNOT_MODIFY: 'BOT_ENABLED_CANNOT_MODIFY',
  BOT_NOT_FOUND: 'BOT_NOT_FOUND',
  BOT_WALLET_DEPLOYING: 'BOT_WALLET_DEPLOYING',
  BOT_WALLET_INSUFFICIENT_BALANCE: 'BOT_WALLET_INSUFFICIENT_BALANCE',
  BOT_WALLET_MARKET_IN_USE: 'BOT_WALLET_MARKET_IN_USE',
} as const

// Bridge errors
const BRIDGE_ERRORS = {
  BRIDGE_FETCH_ASSETS_FAILED: 'BRIDGE_FETCH_ASSETS_FAILED',
  BRIDGE_QUOTE_FAILED: 'BRIDGE_QUOTE_FAILED',
  BRIDGE_WITHDRAW_FAILED: 'BRIDGE_WITHDRAW_FAILED',
} as const

// Wallet errors
const WALLET_ERRORS = {
  WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
  WALLET_ALREADY_IN_USE: 'WALLET_ALREADY_IN_USE',
  WALLET_CREATION_FAILED: 'WALLET_CREATION_FAILED',
  WALLET_DEPLOYING: 'WALLET_DEPLOYING',
  WALLET_HAS_BOTS: 'WALLET_HAS_BOTS',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_INVALID_PRIVATE_KEY: 'WALLET_INVALID_PRIVATE_KEY',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_WITHDRAW_FAILED: 'WALLET_WITHDRAW_FAILED',
} as const

// Strategy errors
const STRATEGY_ERRORS = {
  STRATEGY_ALREADY_EXISTS: 'STRATEGY_ALREADY_EXISTS',
  STRATEGY_HAS_BOTS: 'STRATEGY_HAS_BOTS',
  STRATEGY_INTERVAL_NOT_MODIFIABLE: 'STRATEGY_INTERVAL_NOT_MODIFIABLE',
  STRATEGY_INVALID_JSON: 'STRATEGY_INVALID_JSON',
  STRATEGY_NO_BUY_STEPS: 'STRATEGY_NO_BUY_STEPS',
  STRATEGY_NOT_FOUND: 'STRATEGY_NOT_FOUND',
} as const

// Subscription errors
const SUBSCRIPTION_ERRORS = {
  SUBSCRIPTION_BOT_LIMIT_EXCEEDED: 'SUBSCRIPTION_BOT_LIMIT_EXCEEDED',
  SUBSCRIPTION_STATS_ACCESS_DENIED: 'SUBSCRIPTION_STATS_ACCESS_DENIED',
  SUBSCRIPTION_STRATEGY_BUY_SIZE_EXCEEDED: 'SUBSCRIPTION_STRATEGY_BUY_SIZE_EXCEEDED',
  SUBSCRIPTION_STRATEGY_LIMIT_EXCEEDED: 'SUBSCRIPTION_STRATEGY_LIMIT_EXCEEDED',
  SUBSCRIPTION_WALLET_LIMIT_EXCEEDED: 'SUBSCRIPTION_WALLET_LIMIT_EXCEEDED',
} as const

// Payment errors
const PAYMENT_ERRORS = {
  PAYMENT_CHARGE_CREATION_FAILED: 'PAYMENT_CHARGE_CREATION_FAILED',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
} as const

// Internal API errors
const INTERNAL_API_ERRORS = {
  INTERNAL_API_KEY_INVALID: 'INTERNAL_API_KEY_INVALID',
  INTERNAL_API_KEY_MISSING: 'INTERNAL_API_KEY_MISSING',
} as const

// Combine all error codes
export const ERROR_CODES = {
  ...BASIC_ERROR_CODES,
  ...AUTH_ERROR_CODES,
  ...BOT_ERRORS,
  ...BRIDGE_ERRORS,
  ...WALLET_ERRORS,
  ...STRATEGY_ERRORS,
  ...SUBSCRIPTION_ERRORS,
  ...PAYMENT_ERRORS,
  ...INTERNAL_API_ERRORS,
} as const

export type ErrorCode = keyof typeof ERROR_CODES
